### ISSUE TITLE
Investigate the ability to auto-connect users from MM to Teams

### ISSUE THREAD

**Issue by mkdbns** [mattermost/mattermost-plugin-msteams-sync#102]

**Comment by manojmalik20** [comment]
After a lot of investigation, we found that it is not possible to call the Microsoft Graph APIs without an access token for the resources that we need. The most we can do is get an access token for the application and use that. In fact, we are using that for many purposes in the plugin, but there are some APIs that are protected and require a token that has user authentication also. See this [link](https://learn.microsoft.com/en-us/graph/teams-protected-apis) for more info on such APIs.

I found an option called `On-Behalf-Of` flow that seemed like the solution but that is also not suitable for our use. See this [link](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow) for more details. It lets one app call an API on behalf of another app but we still require user-level authentication to get the value for the `assertion` field. 

So, we've concluded that it is not possible to auto-connect users.

**Comment by manojmalik20** [comment]
Here are some of the APIs that the plugin is using which require user-level authentication:

- [Get chatMessage](https://learn.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&tabs=http): This API is called when we get a change notification from MS Graph but we don't get the message content, so we need to make a separate API call to get the content of the message.
- [ListJoinedTeams](https://learn.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http): This API is called when the user tries to link a Mattermost channel to an MS Teams channel. We need to list all the teams that he's a member of.
- [ListChannelsInTeam](https://learn.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=go): This API is called when the user tries to link a Mattermost channel to an MS Teams channel.
- [SendMessageInChannelOrChat](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http): This API is called whenever we have to post a message in MS Teams on behalf of a user.
- [SetReaction](https://learn.microsoft.com/en-us/graph/api/chatmessage-setreaction?view=graph-rest-beta): This API is called to set a reaction on a post in MS Teams whenever a reaction is added on a post in Mattermost.

Above are some of the APIs that need user authentication. There are many more. It is not possible to call these APIs with an application-level token and perform the tasks on behalf of the user. That's why it is necessary to make the user go through the OAuth flow and grant us access to use his OAuth token.
