### ISSUE TITLE
Inconsistent behaviour of DM's and group messages of users not connecting on Teams

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#103]
If a user tries to DM or send a message in a group in Teams, then to sync it on the MM channel, at-least any of the one user, whether the author or the receiver needs to be connected, and the desired message will be also posted in MM channel.
Whereas, when the user tries to post a DM or group message in MM, then the author needs to be mandatory connected to the Teams so that the same message can be reflected on Teams as well.

Instead, the actual behaviour should have been that either both (every in case of group messages) needs to be connected to sync the messages on Teams from MM, or only single user(whether author or receiver)needs to be connected to sync the messages.

**Comment by manojmalik20** [comment]
When trying to reproduce this issue on the latest main branch, we observed that the behavior has changed from the description here. Now, if a user posts a message in a DM in Mattermost and he is connected, even then the message is not synced to Teams if the receiver has not connected his account even once. If the receiver would have connected his account in the past, then his corresponding Teams user id would have persisted in the store and the plugin would have been able to use it.

**What should be the correct behaviour:**
If the receiver is not connected or hasn't connected his account even once in the past, then the plugin should fetch the Teams user corresponding to the user's email and should use that id to find the DM channel on Teams. If no user exists on Teams with the same email then the error should be logged.

**Comment by manojmalik20** [comment]
When a user posts a message in a DM in Teams, the plugin checks if any member of the chat (either sender or receiver) is connected or not. If yes, it fetches the message content using that connected member's token and posts a message on Mattermost from the author's account.

We cannot do this in case of "Mattermost to Teams" because it is not possible to impersonate a user in Teams (for now). That's why the plugin uses a bot account, but the bot account cannot post in a DM because a DM consists only two members. If we add the bot account in the chat, then it becomes a group chat. So, our solution is.. if a Mattermost user tries to DM a user on Mattermost with his account not connected, then we can prompt him via an ephemeral post that if he wants his message to sync on Teams as well, he needs to connect his account. What are your thoughts @jespino?

**Comment by jespino** [comment]
That can get pretty annoying pretty fast. I would say something like. If you want to send a direct message to a synthetic user in mattermost and your account is not connected to msteams, you should notify that and reject the message.

But I don't think we necessarily need to propagate message to msteams between real mattermost users if they are not connected to MSTeams. The warning can be there maybe once, or once per month, or something like that, but doing that every message can drive anybody crazy.

Actually, this is one of the reasons behind my decision to include this "enforce connected accounts" settings that force you to connect your account before use it.
