### ISSUE TITLE
Editing markdown converts it to HTML

### ISSUE THREAD

**Issue by mkdbns** [mattermost/mattermost-plugin-msteams-sync#209]
Carrie encountered what might be an issue worth fixing:

1. Compose a message in Mattermost in a linked channel that contains Markdown-formatted text.
2. Make a single edit to that text.
3. Note that both the Mattermost result and the MS Teams result converts the once-working Markdown formatting to HTML.

![Image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/6202025/c4a0c1e8-10fe-4c5f-a673-9fa38780f52f)

**Comment by ayusht2810** [comment]
[screen-capture (28).webm](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/100013900/947e3635-9b1f-463e-adc3-0aa1f9dc48be)

Tested the above issue on the latest changes, and the issue was not reproducible. The issue was reproducible on the latest release build. The above issue will be fixed when creating a new release. Closing the issue now.
