### ISSUE TITLE
Subscriptions are not being created/renewed properly

### ISSUE THREAD

**Issue by manojmalik20** [mattermost/mattermost-plugin-msteams-sync#54]
After two channels are linked, messages are synced between MM and Teams with no issues. If we leave the system idle for few minutes, the messages from Teams to MM stop syncing. The following error was shown in the server logs:
```
Unable to create the new subscription         caller="app/plugin_api.go:976" plugin_id=com.mattermost.msteams-sync error="503 Service Unavailable: {"error":{"code":"UnknownError","message":"","innerError":{"client-request-id":"da925406-c994-4c23-ac2f-7fd5de6df45c","date":"2023-04-04T10:15:27","request-id":"da925406-c994-4c23-ac2f-7fd5de6df45c"}}}"
error [2023-04-04 15:45:27.287 +05:30] Unable to subscribe to channels               caller="app/plugin_api.go:976" plugin_id=com.mattermost.msteams-sync error="503 Service Unavailable: {"error":{"code":"UnknownError","message":"","innerError":{"client-request-id":"da925406-c994-4c23-ac2f-7fd5de6df45c","date":"2023-04-04T10:15:27","request-id":"da925406-c994-4c23-ac2f-7fd5de6df45c"}}}"
```

After this error, even if we unlink the channels and link again, the subscription will not be created and the messages from Teams will not be synced to Mattermost.

**Comment by jespino** [comment]
The solution to this is creating a retry mechanism in the client library, see it here: https://learn.microsoft.com/en-us/graph/errors#http-status-codes

That is in my plans, but is not a high priority right now.

I don't think it is a bug, it is more an enhancement. What do you think @mkdbns?

**Comment by mkdbns** [comment]
This may be resolved with the migration to the official SDK. Is there a way we can validate this (simulate 503 from Teams)?

**Comment by mkdbns** [comment]
Maybe using something like this: https://github.com/Shopify/toxiproxy

**Comment by ayusht2810** [comment]
@jespino I was working on this issue and found the subscriptions were not being renewed and deleted properly due to an incorrect `baseURL` sent from the `monitor` package to renew the subscriptions. You can refer to the below image for this
![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/100013900/7352dd04-1513-413f-8f16-54313400b279)
I fixed this by fixing the `baseURL`.
But still, the subscriptions were not getting renewed properly and I was getting this in my server logs
![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/100013900/728419a5-942f-4045-b51c-c8efe8670679)
I tried finding the original error behind this and got this
![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/100013900/17920465-399f-449e-9b7a-f7f2d2ce3ddb)
The subscriptions created during the start of the plugin were working fine but when I tried to get the list of subscriptions using `MS Graph API explorer` I was getting an empty list. I also tried fetching the subscription using the `subscription ID` from `MS Graph API Explorer` but was not able to fetch those as well due to which we are not able to renew/delete the subscriptions.
Do you know about any of this behavior?

**Comment by ayusht2810** [comment]
@jespino I got the list of subscriptions by granting some permissions but fetching the subscription using the `subscription ID` from `MS Graph API Explorer` was still returning `ResourceNotFound` error.

**Comment by ayusht2810** [comment]
@jespino @mkdbns posted a question on the community regarding this issue [here](https://learn.microsoft.com/en-us/answers/questions/1285830/not-able-to-get-subscription-by-subscription-id-fr)

**Comment by ayusht2810** [comment]
Subscriptions are being created/renewed properly. We are no longer getting the above errors in the logs. Closing the issue.
