### ISSUE TITLE
Messages not visible on Teams if the user is not connected

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#66]
If any desired user is not connected to Teams, the messages done by that particular user on Mm are not visible on Teams. But opposite of this is true(if a user do a message on Teams and the user is not connected, still the messages are visible on MM channel.)

**Steps to reproduce:-**
1. Add any test message on MM channel by the user who is not connected to Teams.
2. Verify the same message on Teams.

The message done by the user who is not connected is not visible on the Teams channel. 

![image](https://user-images.githubusercontent.com/116162036/230055869-ab567939-2513-4aa7-8d3e-9a671ef85bb6.png)

![image](https://user-images.githubusercontent.com/116162036/230055918-585454cb-0005-4610-9b38-565c4e17bda6.png)

**Comment by mkdbns** [comment]
Related to #60

**Comment by ayusht2810** [comment]
@jespino I was working on this issue and found that the message was not being posted because the user was not connected so we couldn't fetch the token. I tried changing the client used for that API to use application-level API and giving `Teamwork.Migrate.All` permission to the API. But got the error `Message POST is allowed in application-only context only for import purposes.` but found application permissions are only supported for migration purposes. So we need the delegated level API. You can read more about it here https://learn.microsoft.com/en-us/answers/questions/1168205/i-cant-send-message-in-chat-with-microsoft-graph-a
https://learn.microsoft.com/en-gb/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams

So it's not possible to post a message if the user is not connected. We can post a message in teams by connecting a bot account and posting the message on behalf of the user by using the bot account. 
![image](https://user-images.githubusercontent.com/100013900/232403027-6d3ce866-d404-4ef2-a27b-ef5cc897cb25.png)
